Feature retrieve room
wisaTong/Saltwater pull request #43
Opened 2018-11-28 18:05 UTC by patompong995

This feature for get data from firebase.

2018-11-28 18:23 UTC, wisaTong requested changes
Having unittest would be appreciate

2018-11-28 18:23 UTC, wisaTong commented on app/services/FirebaseService.scala
> +      override def onCancelled(error: DatabaseError): Unit = {}
Log error out

2018-11-28 18:23 UTC, wisaTong commented on app/services/FirebaseService.scala
> +    val ref2 = ref.child("Room").child("Create")
bad variable name `ref2`. please rename.

2018-11-28 18:23 UTC, wisaTong commented on app/services/FirebaseService.scala
> +  def retrieving() = {
rename function to be more meaningful

2018-11-28 18:23 UTC, wisaTong commented on app/services/FirebaseService.scala
> +          ChatSystem.createRoom(data.getValue(classOf[String]))
single statement expression can be written without { }. make it a one liner.

2018-11-29 06:33 UTC, wisaTong requested changes
Overall everything looks good. but please fixed `save` method

2018-11-29 06:33 UTC, wisaTong commented on app/services/FirebaseService.scala
>      ref.updateChildrenAsync(data.asJava)
Because you change Database reference from `"chat/Room"` to `"chat"` this will cause bug on `def save`

2018-11-29 06:33 UTC, wisaTong commented on app/services/FirebaseService.scala
> +  def chatroomRetrieving() = {
Suggestion: `def retrieveChatRooms`

2018-11-30 04:22 UTC, booknap submitted a review, later dismissed
LGTM

2018-11-30 04:47 UTC, wisaTong approved these changes

2018-11-30 04:47 UTC, merged